#!/bin/sh
### BEGIN INIT INFO
# Provides:          mensabot
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/Stop tu_mensabot
# Description:       Start/Stop tu_mensabot Telegram bot.
### END INIT INFO

# Inspired by https://github.com/fhd/init-script-template/blob/master/template

NAME="mensabot"
CLEAR_NAME="TU Mensabot"
DIR="/usr/local/bin/bots/$NAME"
LOGFILE="/var/log/bots/$NAME.log"
PIDFILE="/var/run/$NAME.pid"

get_pid() {
    cat "$PIDFILE"
}

is_running() {
    [ -f "$PIDFILE" ] && kill -0 $(get_pid) > /dev/null 2>&1
}

start() {
    if is_running; then
        echo "$CLEAR_NAME already running."
    else
        echo "Starting $CLEAR_NAME ..."
        # Create log
        mkdir -p "$(dirname $LOGFILE)"
        cd "$DIR"
        # Start bot
        nohup python3 mensabot.py < /dev/null >> "$LOGFILE" 2>&1 &
        echo $! > "$PIDFILE"
        # Check if successful
        if ! is_running; then
            echo "Failed to start $CLEAR_NAME, see $LOGFILE."
            exit 1
        fi
        echo "Started $CLEAR_NAME."
    fi
}

update_menu() {
    cd "$DIR"
    python3 run_menu_update.py 2>> "$LOGFILE"
}

stop() {
    if ! is_running; then
        echo "$CLEAR_NAME is not running."
    else
        echo "Stopping $CLEAR_NAME ..."
        kill -15 $(get_pid)
        rm "$PIDFILE"
        echo "Stopped $CLEAR_NAME."
    fi
}

status() {
    if is_running; then
        echo "$CLEAR_NAME is running."
    else
        echo "$CLEAR_NAME stopped."
        exit 1
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    status)
        status
        ;;
    update)
        stop
        update_menu
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status|update}"
        ;;
esac

exit 0
